export default function PrivacyPage(){
 const operator=process.env.NEXT_PUBLIC_PRIVACY_OPERATOR;
 const email=process.env.NEXT_PUBLIC_PRIVACY_EMAIL;
 return <main className="privacy-page"><a href="/">Back to Pixel Dex</a><h1>Privacy notice</h1><p>Updated September 12, 2026</p>{(!operator||!email)&&<p role="status"><strong>Draft — operator and contact details must be completed before this notice is published.</strong></p>}
 <h2>Who operates Pixel Dex</h2><p>{operator||'Operator details pending.'} {email&&<>For privacy questions or requests, email <a href={'mailto:'+email}>{email}</a>.</>}</p>
 <h2>Information you provide</h2><p>Pixel Dex stores your account identifier and email, your collection of games and hardware, wishlists, progress, ratings, notes, PC components and upgrade history, lists, profile details, favorites, and display preferences. Google sign-in may provide basic profile information to our authentication provider. Google passwords are not shared with Pixel Dex.</p>
 <h2>How information is used</h2><p>We use this information to sign you in, save and synchronize your collection, provide the sharing settings you choose, retrieve catalog information, and protect the service from abuse. Email/password sign-in is processed through our server and Supabase; the application does not log your password or session tokens.</p>
 <h2>What other people can see</h2><p>Your claimed profile name, biography, and top six games are publicly visible. A public collection shares titles, platforms, item types, and ownership or wishlist status; personal collection notes, reviews, and upgrade history are excluded.</p><p>Public lists appear on your profile. Unlisted lists are absent from your public profile but anyone with the link can read them and pass the link on. Private lists are visible only to you. List descriptions and game notes follow the list's visibility. Content someone already viewed, downloaded, or copied cannot be recalled by changing visibility.</p>
 <h2>Service providers and external images</h2><p>Supabase provides authentication and database storage. Cloudflare hosts Pixel Dex and processes network requests. Google handles Google sign-in when selected. Game searches and catalog lookups are sent through our server to IGDB/Twitch; your library notes and account email are not sent with those searches. Loading game covers may contact IGDB's image host or Steam's image host, which receives the network information needed to deliver an image, including your IP address. These providers may process information in countries other than your own.</p>
 <h2>Browser storage and technical records</h2><p>We use browser storage for your session, a separate local library when used, and account-specific recovery drafts. Shared devices can retain these copies. We record server failures by service category and HTTP status; these application records omit request bodies, query strings, account identifiers, and collection contents. Cloudflare and Supabase may retain operational and security logs under their own settings and policies. The application uses a hashed IP identifier and recent attempt times to enforce password-login limits. Pixel Dex currently has no advertising or analytics trackers added by the application.</p>
 <h2>Retention, exports, and deletion</h2><p>Cloud account data is kept while your account exists unless you remove individual records. Settings provides a collection backup export. Delete account removes your active authentication record and its linked library, profile, and lists, and clears the current account's recovery draft and session in the browser used for deletion.</p><p>Deletion does not erase downloaded backups, the separate local library, copies held by other people, or browser data on devices we cannot reach. Provider backups and logs may remain until their retention periods expire; we do not promise immediate removal from those systems. Re-registering creates a new account and does not restore the deleted collection.</p>
 <h2>Your choices</h2><p>You can edit your records and sharing settings, export your collection, sign out, or request account deletion. Depending on where you live, you may have additional rights to access, correct, restrict, or delete personal information. Contact the operator for requests you cannot complete in the app.</p>
 <h2>Provider information</h2><ul><li><a href="https://supabase.com/privacy">Supabase privacy policy</a></li><li><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy policy</a></li><li><a href="https://policies.google.com/privacy">Google privacy policy</a></li><li><a href="https://www.twitch.tv/p/en/legal/privacy-notice/">Twitch privacy notice</a></li></ul></main>;
}
